### ISSUE TITLE
insurance problems 

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#229]
Trying to sign up a new client and add insurance, she lives in FL and this is what DB is saying:
![sam](https://cloud.githubusercontent.com/assets/8440903/6489794/5010a140-c26f-11e4-80a6-41ac0d1d6df0.png)

**Comment by bradatkins** [comment]
Fixed.

![image](https://cloud.githubusercontent.com/assets/8440255/6653239/e7c2e9f6-ca5f-11e4-97c5-b066f6465eac.png)

**Comment by ali206** [comment]
Didn't work for Irena today:

![capture](https://cloud.githubusercontent.com/assets/8440903/6668318/737871c8-cbc8-11e4-93bb-b8a97c297a84.PNG)

**Comment by bradatkins** [comment]
I noticed the state drop down missing.

If you/someone else tries it, same result?

**Comment by ali206** [comment]
I just tested a new registration under my name but with same address as above from Irena and it didn't work:

1st pic state shows up
![image](https://cloud.githubusercontent.com/assets/8440903/6676659/f6de0f50-cbff-11e4-90ba-e4832c32f982.png)

Then after i click review purchase this pops up:
![image](https://cloud.githubusercontent.com/assets/8440903/6676685/2e9056ce-cc00-11e4-9f02-13af8a1b4c40.png)

**Comment by ali206** [comment]
Hi Brad, 

Any way to work on this ASAP? Still not working on clients end, which means we have many clients unable to register themselves.  And still not working on our end properly. 

thanks!

**Comment by bradatkins** [comment]
I've temporarily disabled this check...

**Comment by bradatkins** [comment]
I think I've got this fixed, but I'm going to monitor it still for a few days.
