### ISSUE TITLE
417225 - SS not calculating in 

### ISSUE THREAD

**Issue by ali206** [206Tours/DB#269]
for Luca: 

![image](https://cloud.githubusercontent.com/assets/8440903/6600268/03f3f192-c7e5-11e4-90a5-e301bc469c31.png)

**Comment by bradatkins** [comment]
Fixed.

Odd that it wouldn't just be selected as a SS with the order, rather then an additional cost?

![image](https://cloud.githubusercontent.com/assets/8440255/6652010/00a25996-ca35-11e4-90d0-46e3283bf96d.png)

**Comment by ali206** [comment]
It was originally selected that way but it wasn't showing on the invoice so i manually added it to the invoice

**Comment by bradatkins** [comment]
Luca's  room type was set to double? I set it to single and it showed up fine?

![image](https://cloud.githubusercontent.com/assets/8440255/7101569/0efa6e9e-e02d-11e4-993d-11adbc6570bb.png)

![image](https://cloud.githubusercontent.com/assets/8440255/7101570/12f0a504-e02d-11e4-878f-aadd531de965.png)

**Comment by ali206** [comment]
It was showing when selecting it from within the booking but it wasn't calculating in to total trip costs...and it's still not:

![image](https://cloud.githubusercontent.com/assets/8440903/7138879/fc0919dc-e290-11e4-8a87-a9e631c18f60.png)

**Comment by bradatkins** [comment]
Fixed
