### ISSUE TITLE
New Look - Initial Testing - Default State

### ISSUE THREAD

**Issue by ronenreinheimer** [206Tours/DB#633]
Hi Brad,

When i went to put in my contact information, it showed me the default state as Alaska. Can you please default it to the 2nd SS?

![image](https://cloud.githubusercontent.com/assets/10079829/11483726/0e2b6290-9778-11e5-96cd-76ef11859302.png)

![image](https://cloud.githubusercontent.com/assets/10079829/11483718/01b8492e-9778-11e5-8262-7b67e10e68fa.png)

**Comment by bradatkins** [comment]
Were you registering as a new PAX or returning?

**Comment by ronenreinheimer** [comment]
New, I used a new account ronen3@206tours.com<mailto:ronen3@206tours.com>

Ronen3
Reinheimer3



Wishing you a Blessed Advent,

________________________________
[http://www.206tours.com/sigs/30th-logo2.png]<http://www.206tours.com/>

Ronen Reinheimer
Art Director
206Tours.com<http://www.206tours.com/>

**Comment by ronenreinheimer** [comment]
any update on this issue?

**Comment by bradatkins** [comment]
Not yet. Just compiling a list of issues for now...

**Comment by ronenreinheimer** [comment]
Hi Brad,

any update with this issue? it is making everyone a little bit "crazy"

**Comment by bradatkins** [comment]
So the DB actually defaults the state based on your IP address. For some reason your IP address for 206 Tours returns both New York and Alaska haha.

For 206 Tours staff I'm going to disable this functionality

**Comment by bradatkins** [comment]
Fixed

**Comment by ronenreinheimer** [comment]
OK, super!

Thank you and God Bless,

________________________________
[http://www.206tours.com/sigs/206-logo-sig.png]<http://www.206tours.com/>

Ronen Reinheimer
Art Director
206Tours.com<http://www.206tours.com/>

**Comment by ronenreinheimer** [comment]
Hi Brad, i changed my test booking from what was defaulted as Alaska to New York. then i continued the booking process to the next page - then i pressed the Go Back button and it defaulted back to Alaska:

![image](https://cloud.githubusercontent.com/assets/10079829/12626180/5d9177ec-c505-11e5-853a-64cfc3f0613a.png)

**Comment by ronenreinheimer** [comment]
Hi Brad,

everyone is telling me it is still an issue. please see what you can do.


Thank you and God Bless,

________________________________
[http://www.206tours.com/sigs/206-logo-sig.png]<http://www.206tours.com/>

Ronen Reinheimer
Art Director
206Tours.com<http://www.206tours.com/>
